### ISSUE TITLE
Missing samc.conf

### ISSUE THREAD

**Issue by robmarkcole** [rickardcronholm/CTC_auto#2]
Hi I believe this is the Auxillary file you refer to, could you make available please?
Cheers

File "CTC_auto.py", line 49, in <module>
    with open(confFile) as f:
IOError: [Errno 2] No such file or directory: '/home/ricr/MCQA/samc.conf'

**Comment by rickardcronholm** [comment]
That is one of the auxiliary files, yes. The reason that they are not icluded is that they are site specific. The next version (eta 12th September 2016) will include a dummy set of auxiliary files. The next version will be released under the epl 2.0 license.
